FROM node:20-alpine

WORKDIR /app

# Copiar dependencias de ejecución
COPY package*.json ./
RUN npm install --only=production

# Copiar la aplicación compilada localmente
COPY dist ./dist

# Puerto expuesto por Fastify por defecto
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "dist/server.js"]
